### ISSUE TITLE
Having 1 frames/s 

### ISSUE THREAD

**Issue by sadikozel** [NimmLor/IoT-Audio-Visualization-Center#13]
Hello, When I use audio visualizer it becomes 1 fps somehow. I tried other patterns all of them working fine at 120fps but when I use any volume visualizer it is 1 fps. Is there anyway I can fix this?

![image](https://user-images.githubusercontent.com/72810147/121440166-0e75b200-c990-11eb-9fc7-0a3893fa6049.png)

**Comment by CastleSeven** [comment]
Experiencing the same thing here, any improvements @psilosibin ?

**Comment by sadikozel** [comment]
> Experiencing the same thing here, any improvements @psilosibin ?

Unfortunately, I still have same problem.

**Comment by CastleSeven** [comment]
@psilosibin look here for a fix I found last night - https://github.com/NimmLor/esp8266-fastled-iot-webserver/issues/204

No idea why it works so hopefully it does for you too.

**Comment by sadikozel** [comment]
> @psilosibin look here for a fix I found last night - [NimmLor/esp8266-fastled-iot-webserver#204](https://github.com/NimmLor/esp8266-fastled-iot-webserver/issues/204)
> 
> No idea why it works so hopefully it does for you too.

Thanks a lot. I will try that soon.

**Comment by WarDrake** [comment]
This issue should be solved with the fix from issue #204
