### ISSUE TITLE
App doesn't work with Installer 

### ISSUE THREAD

**Issue by flashez** [NimmLor/IoT-Audio-Visualization-Center#2]
Starting the uwp app after installation doesn't work (nothing happens) when using "IoT-Audio-Visualization-Center_First_Prototype_Installer.zip". Even after restarting computer.

No problem with portable version.

**Comment by NimmLor** [comment]
Very weird, I created the installer directly in Visual Studio 2019, might be a bug because I'm using the developer preview. I'll remove the .zip from the assets and fix in the next release.

**Comment by flashez** [comment]
I’m using VS2019 Enterprise and my .NET frameworks are up to date. I’ll try to build my own.


De : Lorenz Nimmervoll<mailto:notifications@github.com>
Envoyé le :vendredi 8 mai 2020 15:16
À : NimmLor/IoT-Audio-Visualization-Center<mailto:IoT-Audio-Visualization-Center@noreply.github.com>
Cc : flashez<mailto:simi_skate_21@live.fr>; Author<mailto:author@noreply.github.com>
Objet :Re: [NimmLor/IoT-Audio-Visualization-Center] App doesn't work with Installer (#2)


Very weird, I created the installer directly in Visual Studio 2019, might be a bug because I'm using the developer preview. I'll remove the .zip from the assets and fix in the next release.
